version: 2.1

orbs:
  architect: giantswarm/architect@9.5.2

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/go-build:
          name: go-build
          binary: helm-values-gen
          architectures: "linux/amd64,linux/arm64,darwin/amd64,darwin/arm64,windows/amd64,windows/arm64"
          requires:
            - go-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - architect/upload-release-assets:
          context: architect
          binary: helm-values-gen
          requires:
            - go-build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
